import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  CircuitBoardIcon,
  Command,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  LayoutDashboardIcon,
  Loader2,
  LogIn,
  LucideIcon,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Settings,
  SunMedium,
  Trash,
  Twitter,
  User,
  User2Icon,
  UserX2Icon,
  BadgeInfo,
  X,
  HeartHandshake,
  VerifiedIcon,
  BadgeIndianRupee,
  Regex,
  ExternalLink,
  MapPin,
  Coins,
  LineChartIcon,
  Archive,
  Rss,
  Wallet
} from 'lucide-react';
import ReceiptIndianRupee from './icons/receipt-indian-rupee';
import HandCoin from './icons/hand-coin';
import { DashboardIcon } from '@radix-ui/react-icons';

export type Icon = LucideIcon;

export const Icons = {
  dashboard: LayoutDashboardIcon,
  logo: Command,
  login: LogIn,
  close: X,
  profile: User2Icon,
  spinner: Loader2,
  kanban: CircuitBoardIcon,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  employee: UserX2Icon,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  site: MapPin,
  arrowRight: ArrowRight,
  help: HelpCircle,
  info: BadgeInfo,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  support: HeartHandshake,
  billManage: ReceiptIndianRupee,
  verification: VerifiedIcon,
  payment: HandCoin,
  registration: Regex,
  twitter: Twitter,
  check: Check,
  pdfDownload: FileText,
  extraction: ExternalLink,
  report: LineChartIcon,
  batch: Archive,
  blog: Rss,
  wallet: Wallet
};
